name: CI

on: [push, pull_request]

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_BUILD: 'cp*'
        CIBW_SKIP: 'cp36* *musllinux* *_i686 *-win32'
        CIBW_TEST_SKIP: 'cp38*_arm64'

    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: wheels2-${{ matrix.os }}
        path: wheelhouse/*.whl

  merge:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels2
          pattern: wheels2-*
          delete-merged: true

  standard:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15]
        py: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    name: ${{ matrix.os }} py${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    needs: merge
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: checkout monomers
      uses: actions/checkout@v4
      with:
        repository: MRC-LMB-ComputationalStructuralBiology/monomers
        path: monomers

    - uses: actions/download-artifact@v4
      with:
        name: wheels2
        path: wheels2
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }}
    - name: Python Setup
      run: python -m pip install --find-links=wheels2 servalcat
      # add gemmi here to test with gemmi build
    - name: Python Tests
      continue-on-error: true
      env:
        CLIBD_MON: ${{runner.workspace}}/servalcat/monomers
      run: |
        cd tests/
        python3 -m unittest discover -v -s .
        cd ..
